# Generated by Django 5.1.7 on 2025-03-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_conversation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('user_closed', 'User Closed')], default='open', max_length=20),
        ),
    ]
